package com.chart.formatter;

import com.chart.model.AxisValue;

/**
 * Created by kan212 on 17/11/6.
 */

public class SimpleAxisValueFormatter implements AxisValueFormatter {



    @Override
    public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue) {
        return 0;
    }

    @Override
    public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
        return 0;
    }
}
